#!/usr/bin/env node
/**
 * cell_count_histogram.js - prints the cellCount histogram for pannable modes across every
 * screenshots/manifest-*.js currently on disk (generated by tests/exploratory.spec.js's
 * "Random taps (full matrix)" scenario). Same numbers screenshots/index.html now shows visually,
 * for a quick terminal check without opening a browser.
 *
 * Usage: node scripts/cell_count_histogram.js
 */
const fs = require('fs');
const path = require('path');

const SCREENSHOTS_DIR = path.join(__dirname, '..', 'screenshots');
const PANNABLE_MODES = new Set(['sandbox', 'melody', 'compose', 'life']); // see Render.RESTRICTED_MODES

function loadManifest(slug) {
    const file = path.join(SCREENSHOTS_DIR, `manifest-${slug}.js`);
    if (!fs.existsSync(file)) return [];
    const sandboxWindow = { SCREENSHOT_MANIFEST: [] };
    const code = fs.readFileSync(file, 'utf8');
    // eslint-disable-next-line no-new-func
    new Function('window', code)(sandboxWindow);
    return sandboxWindow.SCREENSHOT_MANIFEST;
}

function printHistogram(counts) {
    const buckets = {};
    for (const c of counts) {
        const bucket = Math.floor(c / 25) * 25;
        buckets[bucket] = (buckets[bucket] || 0) + 1;
    }
    const keys = Object.keys(buckets).map(Number).sort((a, b) => a - b);
    for (const k of keys) {
        const n = buckets[k];
        console.log(`  ${String(k).padStart(4)}-${k + 24}: ${'#'.repeat(n)} (${n})`);
    }
    const sorted = [...counts].sort((a, b) => a - b);
    const mid = sorted[Math.floor(sorted.length / 2)];
    console.log(`  n=${counts.length}  min=${Math.min(...counts)}  median=${mid}  max=${Math.max(...counts)}  mean=${(counts.reduce((a, b) => a + b, 0) / counts.length).toFixed(0)}`);
}

for (const slug of ['desktop-chrome', 'mobile-chrome', 'tablet-chrome', 'mobile-safari']) {
    const entries = loadManifest(slug).filter((e) => PANNABLE_MODES.has(e.mode) && e.cellCount != null);
    if (entries.length === 0) { console.log(`\n${slug}: no manifest / no pannable-mode cellCount data`); continue; }
    console.log(`\n${slug} (${entries.length} pannable-mode scenarios):`);
    printHistogram(entries.map((e) => e.cellCount));
}
